# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'IV4lMyTWITXo9TFxmlu4TpLxE5vRA0QV'
  redis: 'G0MQzosDgCOienF8EK53lEcs5XLkY4a6'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'ceyUsOdauCbewRQQHYhqx1IuNuCVuVRW'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'DwVjUOUmfhEEkjye6tLmSApUZ5fXJQDt'
  serviceSecret: '_d14eorKb4AiBnw_cVyT0D8HLW2Qqo4o'

# Passwords used in production mode.
production:
  database: 'crNijlBycn6f-OzRNuPRwsXr_fLLHd4D'
  serviceSecret: '8foWNv1q8v6gdHryXD9p02WKdYBEZV8m'
